title: Moh Roufiq
description: My Personal Blog
author: @roufiq
logo: /hcz-jekyll-blog/static/img/roufiq.jpg
github: https://github.com/roufiq
about: IPDS BPS Kabupaten Simeulue

baseurl: "https://roufiq.github.io/"
url: "https://roufiq.github.io/"

allowsearch: true

disqus_shortname: roufiq
google_analytics: UA-72862926-1

share:
  twitter_username: \roufiq
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
